<a href="https://colab.research.google.com/github/Sebasarthur/ProyectoGrupo2/blob/main/ProyectoGrupo2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('/content/global_unemployment_data.csv')

data = pd.DataFrame(df)

    country_name                    indicator_name     sex age_group  \
234   Costa Rica  Unemployment rate by sex and age  Female     15-24
235   Costa Rica  Unemployment rate by sex and age  Female       25+
236   Costa Rica  Unemployment rate by sex and age  Female  Under 15
237   Costa Rica  Unemployment rate by sex and age    Male     15-24
238   Costa Rica  Unemployment rate by sex and age    Male       25+
239   Costa Rica  Unemployment rate by sex and age    Male  Under 15

    age_categories    2014    2015    2016    2017    2018    2019    2020  \
234          Youth  29.622  26.600  28.011  25.724  31.565  36.008  49.392
235         Adults   6.799   7.313   7.072   7.044   8.050  10.533  16.501
236       Children  10.515  10.375  10.178   9.743  11.442  14.117  21.250
237          Youth  20.825  19.613  17.875  17.816  21.133  27.892  33.532
238         Adults   4.411   4.823   4.798   4.511   5.045   5.439  10.022
239       Children   7.160   7.127   6.782   6.479   7.448   8.506  13.195

       2021    2022    2023    2024
234  46.787  36.780  27.583  25.007
235  15.428  11.868   7.810   7.494
236  20.118  15.185  10.426   9.634
237  33.306  26.276  22.663  23.130
238   8.499   6.110   5.266   4.621
239  11.715   8.635   7.294   6.878

In [91]:
#data frame para filtrar por los paises de centro america

dataCentroAmerica = data.loc[(data['country_name']=='Belize') | (data['country_name']=='Costa Rica')|(data['country_name']=='El Salvador')|(data['country_name']=='Guatemala')|(data['country_name']=='Honduras')|(data['country_name']=='Nicaragua')|(data['country_name']=='Panama')]
dataCentroAmerica.head()

,country_name,indicator_name,sex,age_group,age_categories,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
90,Belize,Unemployment rate by sex and age,Female,15-24,Youth,29.447,26.036,26.503,25.981,28.542,30.771,33.664,29.450,26.750,26.187,26.236
91,Belize,Unemployment rate by sex and age,Female,25+,Adults,9.756,7.187,7.460,5.628,7.549,9.305,11.280,11.364,9.824,9.381,9.215
92,Belize,Unemployment rate by sex and age,Female,Under 15,Children,14.069,11.090,11.181,9.850,11.984,13.905,16.036,15.244,13.268,12.675,12.435
93,Belize,Unemployment rate by sex and age,Male,15-24,Youth,12.119,11.325,11.288,9.787,11.697,13.414,15.305,14.020,12.464,11.861,11.698
94,Belize,Unemployment rate by sex and age,Male,25+,Adults,2.499,3.684,2.409,3.157,3.549,3.831,4.887,4.808,3.838,3.561,3.479

In [ ]:
#data frame para filtrar por los paises de norte america

dataNorteAmerica = data.loc[(data['country_name']=='Canada') | (data['country_name']=='Mexico')|(data['country_name']=='United States')]
dataNorteAmerica.head()

,country_name,indicator_name,sex,age_group,age_categories,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
174,Canada,Unemployment rate by sex and age,Female,15-24,Youth,11.495,10.815,10.726,9.597,9.421,9.371,19.464,12.558,8.941,9.692,10.750
175,Canada,Unemployment rate by sex and age,Female,25+,Adults,5.591,5.515,5.510,5.309,4.880,4.561,7.880,6.483,4.508,4.552,5.129
176,Canada,Unemployment rate by sex and age,Female,Under 15,Children,6.498,6.315,6.280,5.935,5.535,5.269,9.522,7.345,5.138,5.265,5.896
177,Canada,Unemployment rate by sex and age,Male,15-24,Youth,14.901,14.672,14.434,12.837,12.002,12.109,20.822,14.545,11.249,11.406,12.420
178,Canada,Unemployment rate by sex and age,Male,25+,Adults,6.236,6.324,6.627,5.906,5.165,5.097,8.072,6.643,4.525,4.686,5.269

In [83]:
# Lista de países de Sudamérica
paises_suramerica = [
    'Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador',
    'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela','Trinidad and Tobago'
]

#dataframe paises suramerica
dataSurAmerica = data.loc[data['country_name'].isin(paises_suramerica)]

dataSurAmerica.head()

,country_name,indicator_name,sex,age_group,age_categories,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
24,Argentina,Unemployment rate by sex and age,Female,15-24,Youth,22.255,23.710,25.574,26.945,27.870,28.522,34.984,26.703,20.988,20.063,19.932
25,Argentina,Unemployment rate by sex and age,Female,25+,Adults,6.238,6.394,6.724,6.846,7.931,8.138,9.424,7.546,5.944,5.899,5.728
26,Argentina,Unemployment rate by sex and age,Female,Under 15,Children,8.393,8.709,9.225,9.491,10.563,10.712,12.390,9.858,7.689,7.583,7.394
27,Argentina,Unemployment rate by sex and age,Male,15-24,Youth,17.149,18.074,19.355,20.197,21.090,23.983,27.217,20.985,17.637,17.944,17.729
28,Argentina,Unemployment rate by sex and age,Male,25+,Adults,4.671,4.871,5.224,5.389,6.119,6.840,8.480,6.048,4.457,4.621,4.657

In [94]:
#Pais de centroamerica con mayor desempleo en el 2024

idx_max = dataCentroAmerica['2024'].idxmax()

# Usa el índice para obtener la fila completa
dataMaxCen = dataCentroAmerica.loc[idx_max]

dataMaxCen

country_name                                Belize
indicator_name    Unemployment rate by sex and age
sex                                         Female
age_group                                    15-24
age_categories                               Youth
2014                                        29.447
2015                                        26.036
2016                                        26.503
2017                                        25.981
2018                                        28.542
2019                                        30.771
2020                                        33.664
2021                                         29.45
2022                                         26.75
2023                                        26.187
2024                                        26.236
Name: 90, dtype: object

In [96]:
#Pais de norte con mayor desempleo en el 2024

idx_max = dataNorteAmerica['2024'].idxmax()

# Usa el índice para obtener la fila completa
dataMaxNort = dataNorteAmerica.loc[idx_max]

dataMaxNort

country_name                                Canada
indicator_name    Unemployment rate by sex and age
sex                                           Male
age_group                                    15-24
age_categories                               Youth
2014                                        14.901
2015                                        14.672
2016                                        14.434
2017                                        12.837
2018                                        12.002
2019                                        12.109
2020                                        20.822
2021                                        14.545
2022                                        11.249
2023                                        11.406
2024                                         12.42
Name: 177, dtype: object

In [98]:
#Pais de sur con mayor desempleo en el 2024

idx_max = dataSurAmerica['2024'].idxmax()

# Usa el índice para obtener la fila completa
dataMaxSur = dataSurAmerica.loc[idx_max]

dataMaxSur

country_name                              Suriname
indicator_name    Unemployment rate by sex and age
sex                                         Female
age_group                                    15-24
age_categories                               Youth
2014                                        29.929
2015                                        20.756
2016                                        37.338
2017                                         37.33
2018                                        36.567
2019                                         36.26
2020                                          42.3
2021                                         40.38
2022                                        39.715
2023                                        38.984
2024                                        38.111
Name: 960, dtype: object

Authenticated